version: '3.0'

services:
  web:
    build: .
    environment:
      RAILS_ENV: 'development'
      KAFKA_ENDPOINT: '192.168.23.121:9092'
      KAFKA_CLIENT: 'itest'
    ports:
      - 3000:3000
    volumes:
      - .:/rails
